README.md, lib/capybara/screenshot/diff.rb, test/capybara/screenshot/diff_test.rb
README previously suggested setting Capybara::Screenshot.save_path,
but Diff was actually hardcoded to use `doc/screenshot`.
However, Capybara::Screenshot doesn't have a `save_path` config option
anyway, and instead in it's README suggests setting
`Capybara.save_path`.  It seems completely reasonable though, that
users of Capybara::Screenshot::Diff would want screenshots saved to
someplace other than a tmp folder Capybara uses for `save_and_open_page`,
and visa-versa, so, this commit introduces the option, with the default
being the previously hardcoded path to maintain backwards compatability.
=> Support alternate save path for screenshots.

lib/capybara/screenshot/diff/stabilization.rb
Without this patch:
```
Error:
VisualsTest#test_0003_results with resources page:
ArgumentError: wrong number of arguments (given 0, expected 2)
test/system/visuals_test.rb:32:in `block in <class:VisualsTest>'
```
With this patch:
```
VisualsTest#test_0003_results with resources page:
RuntimeError: Could not get stable screenshot within 2s
/Users/zofrex/Code/ruby/hoarders_of_runeterra/doc/screenshots/results_filled_out_x01_1.3s_[752_282_752_282].png~
/Users/zofrex/Code/ruby/hoarders_of_runeterra/doc/screenshots/results_filled_out_x02_2.6s_[924_282_924_282].png~
test/system/visuals_test.rb:32:in `block in <class:VisualsTest>'
```
I think it's fine to delete this line entirely because the same error message is printed out by `check_max_wait_time`, which is the only caller of …
=> Fix error message when a stable screenshot cannot be taken

lib/capybara/screenshot/diff.rb, lib/capybara/screenshot/diff/vcs.rb
If git-lfs is used to store screenshots, then this happens after running tests:
```
Error:
VisualsTest#test_0001_index:
ChunkyPNG::SignatureMismatch: PNG signature not found, found "version " instead of "\x89PNG\r\n\x1A\n"!
```
This is because `git show` on a file tracked by git-lfs doesn't actually give the real file contents, but a pointer to it:
```
% git show HEAD:doc/screenshots/home_page.png 
version https://git-lfs.github.com/spec/v1
oid sha256:bf62a87e2fd46bfd92b661e4128a3fc825e7c776d3ddab10fa124f255219dd39
size 677770
```
This patch is my first attempt to add optional LFS support. I've tested it and it works, but I'm not attached to the code nor the approach - I just needed something working ASAP to fix my build after I added LFS!
Additionally I want to mention that I found it …
=> Support checking out old screenshots via LFS

.rubocop_todo.yml, lib/capybara/screenshot/diff/stabilization.rb
Remove dependency on jQuery in caret hiding code so it works on any website.
Enabling `Capybara::Screenshot.hide_caret = true` on my Rails app gave the following error:
```
Error:
VisualsTest#test_0001_index:
Selenium::WebDriver::Error::JavascriptError: javascript error: $ is not defined
(Session info: chrome=86.0.4240.75)
test/system/visuals_test.rb:9:in `block in <class:VisualsTest>'
```
This is because there is an undeclared dependency on jQuery for this feature, and my website does not have jQuery installed.
I've made an attempt to change this feature to not depend on jQuery. Please let me know what you think!
Of note is that this new behaviour is not 1:1 with the original. I believe the original visits every node in the DOM and applies a style to it, whereas this code declares the …
=> Remove dependency on JQuery for hiding the caret

lib/capybara/screenshot/diff.rb, lib/capybara/screenshot/diff/drivers/chunky_png_driver.rb, lib/capybara/screenshot/diff/drivers/vips_driver.rb, lib/capybara/screenshot/diff/image_compare.rb
I wanted to see which areas were skipped during comparison so I added an orange rectangle for each skip_area.
During testing on master in a real-world project I also found some bugs, mostly for ChunkyPNG.
=> Draw skip_areas + some fixes after trying to use master on a project

lib/capybara/screenshot/diff/test_methods.rb, test/capybara/screenshot/diff/test_methods_test.rb
```
Minitest::UnexpectedError: NoMethodError: undefined method `to_top_left_corner_coordinates' for [150.0, 250.0, 890.0, 270.0]:Array
memo.draw_rect([0, 0, 0, 0], *region.to_top_left_corner_coordinates, fill: true)
```
=> Bug: undefined method with stability_time_limit: true

lib/capybara/screenshot/diff/image_compare.rb, lib/capybara/screenshot/diff/test_methods.rb
I tried to run the repository's tests by cloning, doing `bundle install`, and `rake test:integration` but I get the following error:
https://gist.github.com/asavageiv/99e395bf46c950f114f7e2326fbab482
Is there an ENV I need to set?
In my own repository when using `skip_area` with a CSS selector I'm getting the following errors.
Using a string for `skip_area` leads to this error:
```
Failure/Error: screenshot 'new-property', skip_area: '#property-short-code'
NoMethodError:
undefined method `reduce' for "#property-short-code":String
Did you mean?  rescue
```
Using an array leads to this error:
```
Failure/Error: screenshot 'new-property', skip_area: ['#property-short-code']
NoMethodError:
undefined method `to_top_left_corner_coordinates' for "#property-short-code":String
```
Related to …
=> skip_area with CSS selectors is not working

.github/workflows/test.yml, .gitignore, Rakefile, lib/capybara/screenshot/diff.rb, lib/capybara/screenshot/diff/browser_helpers.rb, lib/capybara/screenshot/diff/drivers/chunky_png_driver.rb, lib/capybara/screenshot/diff/drivers/vips_driver.rb, lib/capybara/screenshot/diff/image_compare.rb, lib/capybara/screenshot/diff/stabilization.rb, lib/capybara/screenshot/diff/test_methods.rb, sig/lib/capybara/screenshot/diff.rbs, sig/lib/capybara/screenshot/diff/browser_helpers.rbs, sig/lib/capybara/screenshot/diff/drivers/base_driver.rbs, sig/lib/capybara/screenshot/diff/drivers/chunky_png_driver.rbs, sig/lib/capybara/screenshot/diff/drivers/utils.rbs, sig/lib/capybara/screenshot/diff/drivers/vips_driver.rbs, sig/lib/capybara/screenshot/diff/image_compare.rbs, sig/lib/capybara/screenshot/diff/os.rbs, sig/lib/capybara/screenshot/diff/region.rbs, sig/lib/capybara/screenshot/diff/stabilization.rbs, sig/lib/capybara/screenshot/diff/test_methods.rbs, sig/lib/capybara/screenshot/diff/vcs.rbs, test/capybara/screenshot/diff/drivers/vips_driver_test.rb, test/capybara/screenshot/diff/stabilization_test.rb, test/capybara/screenshot/diff/test_methods_test.rb, test/support/setup_capybara_drivers.rb
Adds RBS files signatures to help IDE to find the problems or find usage of the unstructured scalars. RubyMine do not need any tools to start use them.
After run, found several problems and added hot-fixes:
* There are unused code, which should generate runtime error if it will be executed
* Made explicit boolean returns
* Explicit driver options types to prepare to move into named params
=> Adds RBS signatures to help IDE to find usages and potential errors

.github/workflows/lint.yml, .github/workflows/test.yml, Rakefile, capybara-screenshot-diff.gemspec, gems.rb, lib/capybara/screenshot/diff/image_compare.rb, scripts/benchmark/find_region_benchmark.rb, test/capybara/screenshot/diff/drivers/vips_driver_test.rb, test/system_test_case.rb
* Introduces `bin/rake test:benchmark`
* Adds ruby-3.2 for tests
* Reduces gem package size
=> Adds Benchmark and Tests tunings

lib/capybara/screenshot/diff/drivers/chunky_png_driver.rb, lib/capybara/screenshot/diff/drivers/vips_driver.rb, lib/capybara/screenshot/diff/image_compare.rb, sig/lib/capybara/screenshot/diff/drivers/base_driver.rbs
Also not obscure the difference rectangle border.
=> Draw skip areas only on the actual area and after the difference rectangle to not obscure non-skipped pixels.

README.md
As per https://github.com/donv/capybara-screenshot-diff/issues/75 I have added a small section about configuring the chrome driver for producing consistent screenshot dimensions across retina and non-retina devices.
=> Update readme with retina instructions

lib/capybara/screenshot/diff/drivers/vips_driver.rb, test/capybara/screenshot/diff/image_compare_test.rb
If a spec or test has a very long name or is nested deeply, the temporary path name formed by `Tmpname` (which preserves the directory names but removes the / separators) may exceed the 255 character filename limit present on many Linux filesystems.
This causes an exception like the one below when Vips tries to write the temporary file. Since
1) temporary file is ultimately moved to the target path, which doesn't exceed the length limit (since most of the length is in nested directory strcuture) and
2) `Tmpname` has some logic to avoid name collisions anyway
shortening the `prefix` passed to `Tmpname` to stay well below 255 characters resolves this error.
```
1) email preferences with EMAIL_PREFERENCES doc preferences #edit should not display any doc preference link for non-imaging …
```
=> Fix "unix error: File name too long" when using Vips

.github/workflows/test.yml, lib/capybara/screenshot/diff/drivers/utils.rb, lib/capybara/screenshot/diff/drivers/vips_driver.rb, test/capybara/screenshot/diff/drivers/utils_test.rb, test/capybara/screenshot/diff/drivers/vips_driver_test.rb, test/capybara/screenshot/diff/image_compare_test.rb, test/integration/test_methods_system_test.rb
Allow running tests without VIPS installed.
Retry test once since JRuby runs sometimes time out.
The purpose is to allow new contributors to just check out the project and run the tests.
=> Verify that tests run after checkout.

lib/capybara/screenshot/diff/browser_helpers.rb
This prevents creating a region that is one pixel too small due to rounding down.
Fixes #87
=> Use ceil before converting to an integer in BrowserHelpers.region_for

lib/capybara/screenshot/diff.rb, test/capybara/screenshot/diff_test.rb
When a spec or test would fail from a difference, the following specs/tests would fail with a generic “no base image” error with the stacktrace containing an error stating that the previous test base screenshot was not present:
```
First test failure: 
Minitest::Assertion:
Screenshot does not match for 'features-email_notification_preferences_spec/email_preferences_with__review_requests_should_allow_rescan_customers_to_view_rescan_preference/00_rescan_preference_page_visited' ({"area_size":263590.0,"region":[256.0,19.0,1482.0,234.0],"difference_level":0.006523589743589743})
/home/circleci/project/spec/screenshots/linux/features-email_notification_preferences_spec/email_preferences_with__review_requests_should_allow_rescan_customers_to_view_rescan_preference/00_rescan_preference_page_visite …
```
=> Move screenshot clearing to be before error raise

lib/capybara/screenshot/diff/drivers/chunky_png_driver.rb
```
For Medium Screen Size: 800x600
user     system      total        real
[same images] chunky_png#different?                  9.686865   0.072288   9.759153 (  9.880038)
[same images] vips#different?                        0.305603   0.081643   0.387246 (  0.239499)
[different images] chunky_png#quick_equal?           9.441579   0.037740   9.479319 (  9.558724)
[different images] vips#quick_equal?                 0.405897   0.106966   0.512863 (  0.350765)
****************************************************************************************************
For Small Screen Size: 80x60
user     system      total        real
[same images] chunky_png#different?                  0.188508   0.003100   0.191608 (  0.194047)
[same images] vips#different?                        0.056107 …
```
=> refact: optimizes to save png files

lib/capybara/screenshot/diff.rb, test/capybara/screenshot/diff_test.rb
"OS" feels like a "higher level" path than "driver"
=> Move OS path before driver path

README.md, lib/capybara/screenshot/diff.rb, test/capybara/screenshot/diff_test.rb
We are currently generating screenshots on a separate branch in CI on one of our projects, and it will be useful to have this job be green when functional tests pass, while still generating the full screenshot difference report.
=> Added option `fail_on_difference`

lib/capybara/screenshot/diff/screenshoter.rb, lib/capybara/screenshot/diff/stable_screenshoter.rb, sig/capybara/screenshot/diff/screenshoter.rbs, sig/capybara/screenshot/diff/stable_screenshoter.rbs, test/capybara/screenshot/diff/screenshoter_test.rb, test/capybara/screenshot/diff/stable_screenshoter_test.rb
I'm getting the exception below intermittently when running my tests. The problem is at `screenshoter.rb:119` the `timeout` is `nil` because of this:
```ruby
@screenshoter = Diff.screenshoter.new(capture_options.except(*STABILITY_OPTIONS), driver)
```
I think when I run locally `pending_image` is `nil` so the tests pass, but on CircleCI it's non-`nil` thus the intermittent failure. That is, `timeout` is never checked locally.
@pftg Should `wait` really be excluded from that `capture_options`?
```
Failure/Error:
screenshot "with_ocr_modal_open",
tolerance: success_alert_tolerance,
skip_area: skip_area
ArgumentError:
comparison of Float with nil failed
[Screenshot Image]: /home/circleci/app/tmp/capybara/failures_r_spec_example_groups_the_new_admin_order_line_items_page_with_featurereceiptocr …
```
=> `ArgumentError: comparison of Float with nil failed` in `Screenshoter#wait_images_loaded`

README.md, lib/capybara/screenshot/diff.rb, lib/capybara/screenshot/diff/screenshot_matcher.rb, lib/capybara/screenshot/diff/screenshoter.rb, sig/capybara/screenshot/diff/screenshot_matcher.rbs, test/capybara/screenshot/diff/screenshoter_test.rb
I'm currently evaluating adding this gem for visual regression testing. Thank you for all your work. I was quite worried about the image diffing until I found this gem 🙇.
Most of our screenshots are of different heights. We can just set a rather high screen height. But that would be adding a lot of whitespace to many of the images, and might require the occasional tweaking.
I've seen in the Selenium API that it's possible to send `full_page: true` as an option to [`save_screenshot`](https://www.rubydoc.info/gems/selenium-webdriver/Selenium/WebDriver/TakesScreenshot#save_screenshot-instance_method). Would you welcome a patch where we add it to the `screenshot`-`options` -> `capture_options` -> `Screenshoter#browser_save_screenshot` -> Capybara/Selenium?
(Some more background: …
=> Full page screenshots

lib/capybara-screenshot-diff.rb, lib/capybara/screenshot/diff.rb, lib/capybara_screenshot_diff/minitest.rb
@pftg This makes it easier for the developer to make the change and will make the transition smoother.
@pftg Can you add this?
=> The deprecation message for 'require "capybara-screenshot-diff"' should list the line in the user code where it is called.
